name: rlsim-env
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.8.2
  - pip
  - pymatgen=2023.3.10
  - python=3.10.13=hd12c33a_1_cpython
  - scipy=1.10.1=py310hd5efca6_0
  - toml=0.10.2
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - yaml=0.2.5=h7f98852_2
  - numpy

  - pip:
      - numpy>=1.22.4
      - ase>=3.23.0
      - ipykernel==6.13.0
      - jupyter==1.0.0
      - jupyter-console==6.4.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==1.1.0

